//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6407
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimnorCompiler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LimnorCompiler.Resources1", typeof(Resources1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;startup useLegacyV2RuntimeActivationPolicy=&quot;true&quot;&gt;&lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.0&quot;/&gt;&lt;/startup&gt;
        ///  &lt;runtime&gt;
        ///    &lt;loadFromRemoteSources enabled=&quot;true&quot;/&gt;
        ///  &lt;/runtime&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        internal static string app_config {
            get {
                return ResourceManager.GetString("app_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;asmv1:assembly manifestVersion=&quot;1.0&quot; xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot; xmlns:asmv1=&quot;urn:schemas-microsoft-com:asm.v1&quot; xmlns:asmv2=&quot;urn:schemas-microsoft-com:asm.v2&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;assemblyIdentity version=&quot;1.0.0.0&quot; name=&quot;MyApplication.app&quot;/&gt;
        ///  &lt;trustInfo xmlns=&quot;urn:schemas-microsoft-com:asm.v2&quot;&gt;
        ///    &lt;security&gt;
        ///      &lt;requestedPrivileges xmlns=&quot;urn:schemas-microsoft-com:asm.v3&quot;&gt;
        ///        &lt;requestedExecutionLevel le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appmanifest {
            get {
                return ResourceManager.GetString("appmanifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; AutoEventWireup=&quot;false&quot; CodeBehind=&quot;{0}&quot; Inherits=&quot;{1}&quot; %&gt;.
        /// </summary>
        internal static string aspxHead {
            get {
                return ResourceManager.GetString("aspxHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{690DC1CD-9BD8-4ad7-B50F-1020D5382B79}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassLib {
            get {
                return ResourceManager.GetString("ClassLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{62126016-D579-4190-8EBF-4ACD83F7DC8F}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassLibD {
            get {
                return ResourceManager.GetString("ClassLibD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{3DF2D995-7D2F-4AAC-AB98-8E6A0482F2D5}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Exe&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleApp {
            get {
                return ResourceManager.GetString("ConsoleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{3DF2D995-7D2F-4AAC-AB98-8E6A0482F2D5}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Exe&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleAppD {
            get {
                return ResourceManager.GetString("ConsoleAppD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ////*
        ///	Json Data Binding Library -- An abstract interface to data sources
        ///	Copyright Longflow Enterprises Ltd
        ///	2011
        ///
        ///*/
        ///
        ///abstract class DataSource
        ///{
        ///	abstract public function SetCredential($c);
        ///	abstract public function GetData($tbl, $query, $Sqlparameters);
        ///	
        ///}
        ////*
        ///	generated by components such as EasyDataSet
        ///*/
        ///class DataTableUpdator
        ///{
        ///	public $SourceTableName;
        ///	public $TableName;
        ///	public $NameDelimitBegin;
        ///	public $NameDelimitEnd;
        ///	public $Parameters;
        ///	public $ErrorMessage;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dataSourceInterface_php {
            get {
                return ResourceManager.GetString("dataSourceInterface_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Debug Information from Limnor Studio Web Pages&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///	
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string DebugInfo {
            get {
                return ResourceManager.GetString("DebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////**_______________________________________
        /// *
        /// *    FastJSON,
        /// *	simple and fast Pear Service_JSON encoder/decoder alternative
        /// *	[http://pear.php.net/pepr/pepr-proposal-show.php?id=198]
        /// * ---------------------------------------
        /// * This class is about two time faster than Pear Service_JSON class.
        /// * This class is probably not powerful as Service_JSON but it has
        /// * no dependencies and converts correctly ASCII range 0x00 - 0x1F too.
        /// * There&apos;s any string convertion, just regular RFC specific  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FastJSON_class_php {
            get {
                return ResourceManager.GetString("FastJSON_class_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // json2.js 2011-02-23 Public Domain. No warranty expressed or implied. Use at your own risk. This file has been superceded by http://www.JSON.org/json2.js See http://www.JSON.org/js.html
        ///
        ///var JSONIDENTIFIER=JSONIDENTIFIER||{};var JSON;if(!JSON){JSON={};}
        ///(function(){&apos;use strict&apos;;function f(n){return n&lt;10?&apos;0&apos;+n:n;}
        ///if(typeof Date.prototype.toJSON!==&apos;function&apos;){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+&apos;-&apos;+
        ///f(this.getUTCMonth()+1)+&apos;-&apos;+
        ///f(this.getUTCDate() [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json_min {
            get {
                return ResourceManager.GetString("json_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///    http://www.JSON.org/json2.js
        ///    2011-10-19
        ///
        ///    Public Domain.
        ///
        ///    NO WARRANTY EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.
        ///
        ///    See http://www.JSON.org/js.html
        ///
        ///
        ///    This code should be minified before deployment.
        ///    See http://javascript.crockford.com/jsmin.html
        ///
        ///    USE YOUR OWN COPY. IT IS EXTREMELY UNWISE TO LOAD CODE FROM SERVERS YOU DO
        ///    NOT CONTROL.
        ///
        ///
        ///    This file creates a global JSON object containing two methods: stringify
        ///    and parse.
        ///
        ///        JSON.stringify(value, replacer, space) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json2 {
            get {
                return ResourceManager.GetString("json2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ////*
        ///	Json Data Binding Library -- php implementation
        ///	Copyright Longflow Enterprises Ltd
        ///	2011
        ///
        ///	Provide PHP interface to Json Data Binding.
        ///	It is an interface between data sources (MySQL, SQL Server, etc) and the binding standard
        ///*/
        ///
        ///
        ///
        ///class JsonDataRow
        ///{
        ///	public $ItemArray = array();
        ///	
        ///	public function addValue($v)
        ///	{
        ///		if($this-&gt;ItemArray == null)
        ///		{
        ///			$this-&gt;ItemArray = array($v);
        ///		}
        ///		else
        ///		{
        ///			$this-&gt;ItemArray = array_values($this-&gt;ItemArray);
        ///			$this-&gt;ItemArray[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jsonDataBind_php {
            get {
                return ResourceManager.GetString("jsonDataBind_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ////*
        ///	Json Data Binding Library -- An abstract class for server side processing and make client response
        ///	Copyright Longflow Enterprises Ltd
        ///	2011
        ///
        ///	each server response php page should derive a sub-class from this class
        ///	and implement abstract functions to do processing
        ///*/
        ///
        ///$thisInstance;
        ///
        ///function myErrorHandler($errno, $errstr, $errfile, $errline)
        ///{
        ///	if (!(error_reporting() &amp; $errno)) {
        ///		// This error code is not included in error_reporting
        ///		return;
        ///	}
        ///	$e;
        ///	switch ($errno) {
        ///	c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonProcessPage_php {
            get {
                return ResourceManager.GetString("JsonProcessPage_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ////*
        ///	Json Data Binding Library -- MySQLI data source for php 
        ///	Copyright Longflow Enterprises Ltd
        ///	2011
        ///
        ///	Provide PHP interface between MySQL and PHP Json Data Binding.
        ///	It fetches MySql data and converts to PHP Json objects conforming to Json Data Binding standard.
        ///	It updates MySql database using data from Json objects conforming to Json Data Binding standard.
        ///*/
        ///
        ////*
        ///       NOT_NULL_FLAG = 1                                                                              
        ///       PRI_KEY_FL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jsonSource_mySqlI_php {
            get {
                return ResourceManager.GetString("jsonSource_mySqlI_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{5F8ABC0D-3AF0-4439-A655-2AF7DFFD86C0}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KioskApp {
            get {
                return ResourceManager.GetString("KioskApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{5F8ABC0D-3AF0-4439-A655-2AF7DFFD86C0}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KioskAppD {
            get {
                return ResourceManager.GetString("KioskAppD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///	Html Editor Library -- JavaScript
        ///	Copyright Longflow Enterprises Ltd
        ///	2011
        ///
        ///*/
        ///JsonDataBinding.DialogueBox = {
        ///	//url, center, top, left, width, height, border, borderWidth, icon, resizable, isDialog, hideCloseButtons, ieBorderOffset
        ///	showDialog: function(dlg) {
        ///		var _divDialog;
        ///		var _frmDialog;
        ///		var _docDialog;
        ///		var _frmWait;
        ///		var _docWait;
        ///		var _tdTitle;
        ///		var _imgIcon;
        ///		var _resizer;
        ///		var _api;
        ///		var _imgOK;
        ///		var _onBringToFront;
        ///		var _isIE = JsonDataBinding.IsIE();
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modal {
            get {
                return ResourceManager.GetString("modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // menu.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///JsonDataBinding.DialogueBox={showDialog:function(dlg){var _divDialog;var _frmDialog;var _docDialog;var _frmWait;var _docWait;var _tdTitle;var _imgIcon;var _resizer;var _api;var _imgOK;var _onBringToFront;var _isIE=JsonDataBinding.IsIE();function _showResizer(visible){if(_resizer){if(visible){var pos=JsonDataBinding.ElementPosition.getElementPosition(_divDialog);var zi=JsonDataBinding.getZOrder(_divDialog)+1;var ieOffset=_isIE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modal_min {
            get {
                return ResourceManager.GetString("modal_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ////*
        ///	Edit this file to provide MySQL credential
        ///*/
        ///      /* sample:
        ///      $cr = new Credential();
        ///      $cr-&gt;host = &apos;localhost&apos;;
        ///      $cr-&gt;user = &apos;root&apos;;
        ///      $cr-&gt;password = &apos;123&apos;;
        ///      $cr-&gt;database = &apos;test1&apos;;
        ///      */
        ///?&gt; .
        /// </summary>
        internal static string MySqlCredential_php {
            get {
                return ResourceManager.GetString("MySqlCredential_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;xsd:schema id=&quot;root&quot; xmlns=&quot;&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xsd:import namespace=&quot;http://www.w3.org/XML/1998/namespace&quot; /&gt;
        ///    &lt;xsd:element name=&quot;root&quot; msdata:IsDataSet=&quot;true&quot;&gt;
        ///      &lt;xsd:complexType&gt;
        ///        &lt;xsd:choice maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xsd:element name=&quot;metadata&quot;&gt;
        ///            &lt;xsd:complexType&gt;
        ///              &lt;xsd:sequence&gt;
        ///                &lt;xsd:element name=&quot;va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resxtemplate {
            get {
                return ResourceManager.GetString("resxtemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ////*
        ///	Sql Client Library -- php 
        ///	Copyright Longflow Enterprises Ltd
        ///	2011
        ///
        ///	Independent Sql Client classes for executing Sql queries
        ///*/
        ///
        ///class SqlClientParameter
        ///{
        ///	public $name;
        ///	public $type;
        ///	public $value;
        ///}
        ///
        ///class SqlScriptProcess
        ///{
        ///	public $script;
        ///	public function FindParameterIndex($sql, $i)
        ///	{
        ///		$k;
        ///		while ($i &lt; strlen($sql))
        ///		{
        ///			if ($sql{$i} == &apos;\&apos;&apos;)
        ///			{
        ///				$k = $i;
        ///				while (true)
        ///				{
        ///					$k = strpos($sql, &apos;\&apos;&apos;, $k+1);
        ///					if ($k &lt; 0)
        ///					{
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlClient_php {
            get {
                return ResourceManager.GetString("sqlClient_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ////*
        ///	Web Application 
        ///	Copyright Longflow Enterprises Ltd
        ///	2011
        ///
        ///*/
        ///
        ///class WebApp
        ///{
        ///	public $PhpPhysicalFolder;
        ///	function __construct()
        ///	{
        ///		$this-&gt;PhpPhysicalFolder = dirname(realpath(__FILE__));
        ///	}
        ///	public function GetSessionVariable($name)
        ///	{
        ///		if(isset($_COOKIE[$name]))
        ///		{
        ///			return $_COOKIE[$name];
        ///		}
        ///		return null;
        ///	}
        ///	public function SetSessionVariable($name, $value)
        ///	{
        ///		setrawcookie($name, $value, time()+60*20);
        ///	}
        ///}
        ///function startsWith($haystack,$needle,$case=t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebApp_php {
            get {
                return ResourceManager.GetString("WebApp_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{5F8ABC0D-3AF0-4439-A655-2AF7DFFD86C0}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WinApp {
            get {
                return ResourceManager.GetString("WinApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;3.5&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;9.0.21022&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{5F8ABC0D-3AF0-4439-A655-2AF7DFFD86C0}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WinAppD {
            get {
                return ResourceManager.GetString("WinAppD", resourceCulture);
            }
        }
    }
}
