//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitleAttribute("Tutorial Viewer")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("The utility to view slides")]
[assembly: System.Reflection.AssemblyProductAttribute("Limnor Codeless Visual Programming System")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Longflow Enterprises Ltd")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © Longflow 2010")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.1.*")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.1")]

