//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Windows.Forms;
    using System.IO;
    using System.Drawing;
    using Limnor.Application;
    
    public class FormViewer : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.PictureBox picStop;
        protected internal System.Windows.Forms.PictureBox picPlay;
        protected internal System.Windows.Forms.PictureBox picOpen;
        protected internal System.Windows.Forms.PictureBox picNext;
        protected internal System.Windows.Forms.PictureBox picPrevious;
        protected internal Limnor.Application.ApplicationConfiguration ApplicationConfiguration1;
        protected internal System.Windows.Forms.ToolTip ToolTip1;
        private System.ComponentModel.IContainer components;
        protected internal System.Windows.Forms.Timer Timer1;
        private static FormViewer _DefaultForm;
        private string valueOfProjectName;
        private string valueOfProjectFolder;
        private int valueOfSlideIndex;
        /// <summary>
        /// </summary>
        public FormViewer()
        {
            this.InitializeComponent();
        }
        public static FormViewer DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new FormViewer();
                }
                return _DefaultForm;
            }
        }
        public virtual string ProjectName
        {
            get
            {
                return this.valueOfProjectName;
            }
            set
            {
                this.valueOfProjectName = value;
            }
        }
        public virtual string ProjectFolder
        {
            get
            {
                return this.valueOfProjectFolder;
            }
            set
            {
                this.valueOfProjectFolder = value;
            }
        }
        public virtual int SlideIndex
        {
            get
            {
                return this.valueOfSlideIndex;
            }
            set
            {
                this.valueOfSlideIndex = value;
            }
        }
        public virtual string SlideFilename
        {
            get
            {
                return System.IO.Path.Combine(this.ProjectFolder, string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}{1}{2}{3}", new object[] {
                                this.ProjectName,
                                "_",
                                this.SlideIndex,
                                ".xml"}));
            }
        }
        public virtual string SlideImageFilename
        {
            get
            {
                return System.IO.Path.Combine(this.ProjectFolder, string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}{1}{2}{3}", new object[] {
                                this.ProjectName,
                                "_",
                                this.SlideIndex,
                                ".jpg"}));
            }
        }
        public virtual string SlideInfo
        {
            get
            {
                return string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}{1}{2}", new object[] {
                            this.ProjectName,
                            " - Slide ",
                            this.SlideIndex});
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormViewer));
            this.picStop = new System.Windows.Forms.PictureBox();
            this.picPlay = new System.Windows.Forms.PictureBox();
            this.picOpen = new System.Windows.Forms.PictureBox();
            this.picNext = new System.Windows.Forms.PictureBox();
            this.picPrevious = new System.Windows.Forms.PictureBox();
            this.ApplicationConfiguration1 = new Limnor.Application.ApplicationConfiguration();
            this.components = new System.ComponentModel.Container();
            this.ToolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.Timer1 = new System.Windows.Forms.Timer(this.components);
            ((System.ComponentModel.ISupportInitialize)(picPrevious)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(picNext)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(picOpen)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(picPlay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(picStop)).BeginInit();
            this.SuspendLayout();
            // 
            // picStop
            // 
            this.picStop.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.picStop.BackColor = System.Drawing.Color.WhiteSmoke;
            this.picStop.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picStop.Image = ((System.Drawing.Image)(resources.GetObject("picStop.Image")));
            this.picStop.Location = new System.Drawing.Point(100, 367);
            this.picStop.Name = "picStop";
            this.picStop.Size = new System.Drawing.Size(16, 16);
            this.picStop.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.picStop.TabIndex = 5;
            this.picStop.TabStop = false;
            this.picStop.Click += new System.EventHandler(this.Click_bcdc25a6);
            // 
            // picPlay
            // 
            this.picPlay.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.picPlay.BackColor = System.Drawing.Color.WhiteSmoke;
            this.picPlay.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picPlay.Image = ((System.Drawing.Image)(resources.GetObject("picPlay.Image")));
            this.picPlay.Location = new System.Drawing.Point(78, 367);
            this.picPlay.Name = "picPlay";
            this.picPlay.Size = new System.Drawing.Size(16, 16);
            this.picPlay.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.picPlay.TabIndex = 4;
            this.picPlay.TabStop = false;
            this.picPlay.Click += new System.EventHandler(this.Click_27b5a110);
            // 
            // picOpen
            // 
            this.picOpen.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.picOpen.BackColor = System.Drawing.Color.WhiteSmoke;
            this.picOpen.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picOpen.Image = ((System.Drawing.Image)(resources.GetObject("picOpen.Image")));
            this.picOpen.Location = new System.Drawing.Point(56, 367);
            this.picOpen.Name = "picOpen";
            this.picOpen.Size = new System.Drawing.Size(16, 16);
            this.picOpen.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.picOpen.TabIndex = 3;
            this.picOpen.TabStop = false;
            this.picOpen.Click += new System.EventHandler(this.Click_aaebb30d);
            // 
            // picNext
            // 
            this.picNext.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.picNext.BackColor = System.Drawing.Color.WhiteSmoke;
            this.picNext.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picNext.Image = ((System.Drawing.Image)(resources.GetObject("picNext.Image")));
            this.picNext.Location = new System.Drawing.Point(34, 367);
            this.picNext.Name = "picNext";
            this.picNext.Size = new System.Drawing.Size(16, 16);
            this.picNext.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.picNext.TabIndex = 2;
            this.picNext.TabStop = false;
            this.picNext.Click += new System.EventHandler(this.Click_93158953);
            // 
            // picPrevious
            // 
            this.picPrevious.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.picPrevious.BackColor = System.Drawing.Color.WhiteSmoke;
            this.picPrevious.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picPrevious.Image = ((System.Drawing.Image)(resources.GetObject("picPrevious.Image")));
            this.picPrevious.Location = new System.Drawing.Point(12, 367);
            this.picPrevious.Name = "picPrevious";
            this.picPrevious.Size = new System.Drawing.Size(16, 16);
            this.picPrevious.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.picPrevious.TabIndex = 1;
            this.picPrevious.TabStop = false;
            this.picPrevious.Click += new System.EventHandler(this.Click_1c2b29e8);
            // 
            // Timer1
            // 
            this.Timer1.Interval = 1000;
            this.Timer1.Tick += new System.EventHandler(this.Tick_659a9b1c);
            // 
            // FormViewer
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.BackColor = System.Drawing.Color.White;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.ClientSize = new System.Drawing.Size(631, 395);
            this.Controls.Add(this.picStop);
            this.Controls.Add(this.picPlay);
            this.Controls.Add(this.picOpen);
            this.Controls.Add(this.picNext);
            this.Controls.Add(this.picPrevious);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "FormViewer";
            this.Text = "Tutorial Viewer";
            this.TopMost = true;
            ((System.ComponentModel.ISupportInitialize)(picPrevious)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(picNext)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(picOpen)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(picPlay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(picStop)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
            this.Load += new System.EventHandler(this.Load_b465da4c);
            Limnor.Application.ApplicationConfiguration.LoadingConfigurations += new System.EventHandler(this.LoadingConfigurations_559c999a);
            Limnor.Application.ApplicationConfiguration.SavingConfigurations += new System.EventHandler(this.SavingConfigurations_4c061bd0);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FormClosing_6aa2009d);
        }
        /// <summary>
        /// </summary>
        public virtual void LoadProject()
        {
            FormConfig FormConfig1fb826cae = null;
            FormConfig1fb826cae = new FormConfig();
            FormConfig1fb826cae.LoadConfig(this.ProjectName, this.ProjectFolder, this.SlideIndex);
            System.Windows.Forms.DialogResult retf8198cd1 = FormConfig1fb826cae.ShowDialog(this);
            if ((retf8198cd1 == System.Windows.Forms.DialogResult.OK))
            {
                this.ProjectName = FormConfig1fb826cae.ProjectName;
                this.ProjectFolder = FormConfig1fb826cae.ProjectFolder;
                this.SlideIndex = FormConfig1fb826cae.SlideIndex;
                this.ShowSlide();
            }
        }
        /// <summary>
        /// </summary>
        public virtual void ShowSlide()
        {
            Limnor.Drawing2D.DrawTextRect DrawTextRect121a6cf01 = null;
            this.BackgroundImage = null;
            this.DrawingLayers.ClearDrawings();
            if (System.IO.File.Exists(this.SlideFilename))
            {
                if (System.IO.File.Exists(this.SlideImageFilename))
                {
                    this.BackgroundImage = System.Drawing.Image.FromFile(this.SlideImageFilename);
                }
                this.LoadDrawingsFromFile(this.SlideFilename);
                goto l_ad22d89f;
            }
            else
            {
                this.Timer1.Stop();
                DrawTextRect121a6cf01 = new Limnor.Drawing2D.DrawTextRect();
                DrawTextRect121a6cf01.Rectangle = this.ClientRectangle;
                DrawTextRect121a6cf01.TextFont = new System.Drawing.Font("[FontFamily: Name=Times New Roman]", 27.75F);
                DrawTextRect121a6cf01.TextColor = System.Drawing.Color.FromArgb(((int)(255)), ((int)(0)), ((int)(0)), ((int)(255)));
                DrawTextRect121a6cf01.TextString = "The End";
                this.DrawingLayers.AddDrawing(DrawTextRect121a6cf01);
                goto l_ad22d89f;
            }
        l_ad22d89f:
            this.Refresh();
            this.Text = this.SlideInfo;
            return;
        }
        /// <summary>
        /// </summary>
        public virtual void LoadProjectFromCommand()
        {
            if ((WinFormApp1.CommandArguments.Length > 1))
            {
                this.ProjectName = WinFormApp1.CommandArguments[1];
                if ((WinFormApp1.CommandArguments.Length > 2))
                {
                    this.ProjectFolder = WinFormApp1.CommandArguments[2];
                    goto l_de4b2ba0;
                }
                else
                {
                    this.ProjectFolder = System.IO.Path.Combine(System.IO.Path.GetDirectoryName(System.Windows.Forms.Application.ExecutablePath), "Tutorials");
                    goto l_de4b2ba0;
                }
            }
            return;
        l_de4b2ba0:
            if ((WinFormApp1.CommandArguments.Length > 3))
            {
                this.SlideIndex = System.Convert.ToInt32(WinFormApp1.CommandArguments[3]);
                goto l_9406be67;
            }
            else
            {
                this.SlideIndex = 1;
                goto l_9406be67;
            }
        l_9406be67:
            this.ShowSlide();
            return;
        }
        private void Load_b465da4c(object sender, System.EventArgs e)
        {
            this.ApplicationConfiguration1.ExecuteLoadingConfigurations();
            this.LoadProjectFromCommand();
        }
        private void Click_1c2b29e8(object sender, System.EventArgs e)
        {
            if ((this.SlideIndex > 1))
            {
                this.SlideIndex = (this.SlideIndex - 1);
            }
            this.ShowSlide();
        }
        private void Click_93158953(object sender, System.EventArgs e)
        {
            if (System.IO.File.Exists(this.SlideFilename))
            {
                this.SlideIndex = (this.SlideIndex + 1);
            }
            this.ShowSlide();
        }
        private void Click_aaebb30d(object sender, System.EventArgs e)
        {
            this.LoadProject();
        }
        private void LoadingConfigurations_559c999a(object sender, System.EventArgs e)
        {
            this.ProjectFolder = ((string)(this.ApplicationConfiguration1["Category1"]["Slide Folder"]));
            this.ProjectName = ((string)(this.ApplicationConfiguration1["Category1"]["Slide Name"]));
            this.SlideIndex = ((int)(this.ApplicationConfiguration1["Category1"]["Slide Index"]));
        }
        private void SavingConfigurations_4c061bd0(object sender, System.EventArgs e)
        {
            this.ApplicationConfiguration1["Category1"]["Slide Folder"] = this.ProjectFolder;
            this.ApplicationConfiguration1["Category1"]["Slide Index"] = this.SlideIndex;
            this.ApplicationConfiguration1["Category1"]["Slide Name"] = this.ProjectName;
        }
        private void FormClosing_6aa2009d(object sender, System.Windows.Forms.FormClosingEventArgs e)
        {
            this.ApplicationConfiguration1.ExecuteSavingConfigurations();
        }
        private void Tick_659a9b1c(object sender, System.EventArgs e)
        {
            if (System.IO.File.Exists(this.SlideFilename))
            {
                this.SlideIndex = (this.SlideIndex + 1);
            }
            this.ShowSlide();
        }
        private void Click_27b5a110(object sender, System.EventArgs e)
        {
            this.Timer1.Start();
        }
        private void Click_bcdc25a6(object sender, System.EventArgs e)
        {
            this.Timer1.Stop();
        }
        protected override void Dispose(bool disposing)
        {
            if ((disposing 
                        && (components != null)))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
