//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using System.Drawing;
    
    [System.Drawing.ToolboxBitmapAttribute(typeof(DefaultNamespace.WinFormApp1), "slides.ico")]
    public class WinFormApp1
    {
        protected internal static DefaultNamespace.FormViewer varb0a70936;
        public static DefaultNamespace.FormViewer Page1
        {
            get
            {
                if (((varb0a70936 == null) 
                            || (varb0a70936.IsDisposed == true)))
                {
                    varb0a70936 = new DefaultNamespace.FormViewer();
                }
                return varb0a70936;
            }
        }
        public static string[] CommandArguments
        {
            get
            {
                return System.Environment.GetCommandLineArgs();
            }
        }
        private static void InitializeComponent()
        {
            // 
            // Page1
            // 
            Page1.ClientSize = new System.Drawing.Size(292, 266);
            Page1.Visible = false;
            // 
            // WinFormApp1
            // 
        }
        [STAThread()]
        public static void Main()
        {
            System.Windows.Forms.Application.SetCompatibleTextRenderingDefault(false);
            System.Windows.Forms.Application.EnableVisualStyles();
            InitializeComponent();
            System.Windows.Forms.Application.Run(Page1);
        }
    }
}
