//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using System.Windows.Forms;
    using System.IO;
    using System.Drawing;
    
    public class FormConfig : System.Windows.Forms.Form
    {
        protected internal System.Windows.Forms.Button btPrjName;
        protected internal System.Windows.Forms.Button btFolder;
        protected internal System.Windows.Forms.Button btCancel;
        protected internal System.Windows.Forms.Button btOK;
        protected internal System.Windows.Forms.Label Label3;
        protected internal System.Windows.Forms.TextBox txtIndex;
        protected internal System.Windows.Forms.Label Label2;
        protected internal System.Windows.Forms.TextBox txtFolder;
        protected internal System.Windows.Forms.Label Label1;
        protected internal System.Windows.Forms.TextBox txtName;
        private string valueOfProjectName;
        private string valueOfProjectFolder;
        private int valueOfSlideIndex;
        /// <summary>
        /// </summary>
        public FormConfig()
        {
            this.InitializeComponent();
        }
        public virtual string ProjectName
        {
            get
            {
                return this.valueOfProjectName;
            }
            set
            {
                this.valueOfProjectName = value;
            }
        }
        public virtual string ProjectFolder
        {
            get
            {
                return this.valueOfProjectFolder;
            }
            set
            {
                this.valueOfProjectFolder = value;
            }
        }
        public virtual int SlideIndex
        {
            get
            {
                return this.valueOfSlideIndex;
            }
            set
            {
                this.valueOfSlideIndex = value;
            }
        }
        private void InitializeComponent()
        {
            this.btPrjName = new System.Windows.Forms.Button();
            this.btFolder = new System.Windows.Forms.Button();
            this.btCancel = new System.Windows.Forms.Button();
            this.btOK = new System.Windows.Forms.Button();
            this.Label3 = new System.Windows.Forms.Label();
            this.txtIndex = new System.Windows.Forms.TextBox();
            this.Label2 = new System.Windows.Forms.Label();
            this.txtFolder = new System.Windows.Forms.TextBox();
            this.Label1 = new System.Windows.Forms.Label();
            this.txtName = new System.Windows.Forms.TextBox();
            this.SuspendLayout();
            // 
            // btPrjName
            // 
            this.btPrjName.AllowDrop = true;
            this.btPrjName.Location = new System.Drawing.Point(344, 58);
            this.btPrjName.Name = "btPrjName";
            this.btPrjName.Size = new System.Drawing.Size(24, 23);
            this.btPrjName.TabIndex = 9;
            this.btPrjName.Text = "...";
            this.btPrjName.UseVisualStyleBackColor = true;
            this.btPrjName.Click += new System.EventHandler(this.Click_fde743bd);
            // 
            // btFolder
            // 
            this.btFolder.AllowDrop = true;
            this.btFolder.Location = new System.Drawing.Point(344, 22);
            this.btFolder.Name = "btFolder";
            this.btFolder.Size = new System.Drawing.Size(24, 23);
            this.btFolder.TabIndex = 8;
            this.btFolder.Text = "...";
            this.btFolder.UseVisualStyleBackColor = true;
            this.btFolder.Click += new System.EventHandler(this.Click_3f573b03);
            // 
            // btCancel
            // 
            this.btCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btCancel.Location = new System.Drawing.Point(267, 141);
            this.btCancel.Name = "btCancel";
            this.btCancel.Size = new System.Drawing.Size(75, 23);
            this.btCancel.TabIndex = 7;
            this.btCancel.Text = "&Cancel";
            this.btCancel.UseVisualStyleBackColor = true;
            // 
            // btOK
            // 
            this.btOK.Location = new System.Drawing.Point(181, 141);
            this.btOK.Name = "btOK";
            this.btOK.Size = new System.Drawing.Size(75, 23);
            this.btOK.TabIndex = 6;
            this.btOK.Text = "&OK";
            this.btOK.UseVisualStyleBackColor = true;
            this.btOK.Click += new System.EventHandler(this.Click_5121509e);
            // 
            // Label3
            // 
            this.Label3.AutoSize = true;
            this.Label3.Location = new System.Drawing.Point(27, 105);
            this.Label3.Name = "Label3";
            this.Label3.Size = new System.Drawing.Size(43, 13);
            this.Label3.TabIndex = 5;
            this.Label3.Text = "Slide #:";
            // 
            // txtIndex
            // 
            this.txtIndex.AcceptsTab = true;
            this.txtIndex.Location = new System.Drawing.Point(119, 102);
            this.txtIndex.Name = "txtIndex";
            this.txtIndex.Size = new System.Drawing.Size(223, 20);
            this.txtIndex.TabIndex = 4;
            // 
            // Label2
            // 
            this.Label2.AutoSize = true;
            this.Label2.Location = new System.Drawing.Point(27, 27);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(39, 13);
            this.Label2.TabIndex = 3;
            this.Label2.Text = "Folder:";
            // 
            // txtFolder
            // 
            this.txtFolder.Location = new System.Drawing.Point(119, 24);
            this.txtFolder.Name = "txtFolder";
            this.txtFolder.Size = new System.Drawing.Size(223, 20);
            this.txtFolder.TabIndex = 2;
            // 
            // Label1
            // 
            this.Label1.AutoSize = true;
            this.Label1.Location = new System.Drawing.Point(27, 63);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(64, 13);
            this.Label1.TabIndex = 1;
            this.Label1.Text = "Slide Name:";
            // 
            // txtName
            // 
            this.txtName.Location = new System.Drawing.Point(119, 60);
            this.txtName.Name = "txtName";
            this.txtName.Size = new System.Drawing.Size(223, 20);
            this.txtName.TabIndex = 0;
            // 
            // FormConfig
            // 
            this.ClientSize = new System.Drawing.Size(380, 183);
            this.Controls.Add(this.btPrjName);
            this.Controls.Add(this.btFolder);
            this.Controls.Add(this.btCancel);
            this.Controls.Add(this.btOK);
            this.Controls.Add(this.Label3);
            this.Controls.Add(this.txtIndex);
            this.Controls.Add(this.Label2);
            this.Controls.Add(this.txtFolder);
            this.Controls.Add(this.Label1);
            this.Controls.Add(this.txtName);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FormConfig";
            this.Text = "Tutorial Viewer Configuration";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        /// <summary>
        /// </summary>
        /// <param name="projectName"></param>
        /// <param name="folder"></param>
        /// <param name="slideIndex"></param>
        public virtual void LoadConfig(string projectName, string folder, int slideIndex)
        {
            this.txtName.Text = projectName;
            this.txtFolder.Text = folder;
            this.txtIndex.Text = slideIndex.ToString();
        }
        /// <summary>
        /// </summary>
        public virtual void SelectFolder()
        {
            System.Windows.Forms.FolderBrowserDialog FolderBrowserDialog130e41859 = null;
            FolderBrowserDialog130e41859 = new System.Windows.Forms.FolderBrowserDialog();
            System.Windows.Forms.DialogResult ret6b3b3828 = FolderBrowserDialog130e41859.ShowDialog(this);
            if ((ret6b3b3828 == System.Windows.Forms.DialogResult.OK))
            {
                this.txtFolder.Text = FolderBrowserDialog130e41859.SelectedPath;
                this.txtIndex.Text = "1";
            }
        }
        /// <summary>
        /// </summary>
        public virtual void SelectName()
        {
            DialogSlideName DialogSlideName19120dca7 = null;
            if (System.IO.Directory.Exists(this.txtFolder.Text))
            {
                DialogSlideName19120dca7 = new DialogSlideName();
                DialogSlideName19120dca7.LoadSlideNames(this.txtFolder.Text);
                System.Windows.Forms.DialogResult retad9e845 = DialogSlideName19120dca7.ShowDialog(this);
                if ((retad9e845 == System.Windows.Forms.DialogResult.OK))
                {
                    this.txtName.Text = DialogSlideName19120dca7.SelectedName;
                    this.txtIndex.Text = "1";
                }
            }
        }
        private void Click_5121509e(object sender, System.EventArgs e)
        {
            this.ProjectFolder = this.txtFolder.Text;
            this.ProjectName = this.txtName.Text;
            this.SlideIndex = System.Convert.ToInt32(this.txtIndex.Text);
            this.DialogResult = System.Windows.Forms.DialogResult.OK;
        }
        private void Click_3f573b03(object sender, System.EventArgs e)
        {
            this.SelectFolder();
        }
        private void Click_fde743bd(object sender, System.EventArgs e)
        {
            if (System.IO.Directory.Exists(this.txtFolder.Text))
            {
                this.SelectName();
            }
        }
    }
}
