//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Windows.Forms;
    using System.IO;
    using System.Collections.Specialized;
    using System.Drawing;
    
    public class DialogSlideName : Limnor.Drawing2D.DrawingPage
    {
        protected internal System.Windows.Forms.Button btCancel;
        protected internal System.Windows.Forms.Button btOK;
        protected internal System.Windows.Forms.ListBox ListBox1;
        private static DialogSlideName _DefaultForm;
        private string valueOfSelectedName;
        /// <summary>
        /// </summary>
        public DialogSlideName()
        {
            this.InitializeComponent();
        }
        public static DialogSlideName DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new DialogSlideName();
                }
                return _DefaultForm;
            }
        }
        public virtual string SelectedName
        {
            get
            {
                return this.valueOfSelectedName;
            }
            set
            {
                this.valueOfSelectedName = value;
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DialogSlideName));
            this.btCancel = new System.Windows.Forms.Button();
            this.btOK = new System.Windows.Forms.Button();
            this.ListBox1 = new System.Windows.Forms.ListBox();
            this.SuspendLayout();
            // 
            // btCancel
            // 
            this.btCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btCancel.Location = new System.Drawing.Point(195, 222);
            this.btCancel.Name = "btCancel";
            this.btCancel.Size = new System.Drawing.Size(75, 23);
            this.btCancel.TabIndex = 2;
            this.btCancel.Text = "&Cancel";
            this.btCancel.UseVisualStyleBackColor = true;
            // 
            // btOK
            // 
            this.btOK.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btOK.Location = new System.Drawing.Point(114, 222);
            this.btOK.Name = "btOK";
            this.btOK.Size = new System.Drawing.Size(75, 23);
            this.btOK.TabIndex = 1;
            this.btOK.Text = "&OK";
            this.btOK.UseVisualStyleBackColor = true;
            // 
            // ListBox1
            // 
            this.ListBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
                        | System.Windows.Forms.AnchorStyles.Left) 
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.ListBox1.FormattingEnabled = true;
            this.ListBox1.Location = new System.Drawing.Point(1, 1);
            this.ListBox1.Name = "ListBox1";
            this.ListBox1.Size = new System.Drawing.Size(283, 212);
            this.ListBox1.TabIndex = 0;
            this.ListBox1.SelectedIndexChanged += new System.EventHandler(this.SelectedIndexChanged_5581aa62);
            // 
            // DialogSlideName
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(282, 257);
            this.Controls.Add(this.btCancel);
            this.Controls.Add(this.btOK);
            this.Controls.Add(this.ListBox1);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "DialogSlideName";
            this.Text = "Select Slide Name";
            this.ResumeLayout(false);
        }
        /// <summary>
        /// </summary>
        /// <param name="folder"></param>
        public virtual void LoadSlideNames(string folder)
        {
            string[] files157b6d8a = null;
            System.Collections.Specialized.StringCollection StringCollectionFileNames3a9e25eb = null;
            string filename865b90e0 = null;
            int UnderScorePos2041a161 = 0;
            files157b6d8a = System.IO.Directory.GetFiles(folder, "*.xml");
            StringCollectionFileNames3a9e25eb = new System.Collections.Specialized.StringCollection();
            for (int index_157b6d8a_9d82a78a = 0; (index_157b6d8a_9d82a78a < files157b6d8a.Length); index_157b6d8a_9d82a78a++)
            {
                filename865b90e0 = System.IO.Path.GetFileName(files157b6d8a[index_157b6d8a_9d82a78a]);
                UnderScorePos2041a161 = filename865b90e0.IndexOf('_');
                if ((UnderScorePos2041a161 > 1))
                {
                    filename865b90e0 = filename865b90e0.Substring(0, UnderScorePos2041a161);
                    if ((StringCollectionFileNames3a9e25eb.Contains(filename865b90e0) == false))
                    {
                        StringCollectionFileNames3a9e25eb.Add(filename865b90e0);
                    }
                }
            }
            for (int index_3a9e25eb_93735191 = 0; (index_3a9e25eb_93735191 < StringCollectionFileNames3a9e25eb.Count); index_3a9e25eb_93735191++)
            {
                this.ListBox1.Items.Add(StringCollectionFileNames3a9e25eb[index_3a9e25eb_93735191]);
            }
        }
        private void SelectedIndexChanged_5581aa62(object sender, System.EventArgs e)
        {
            this.SelectedName = this.ListBox1.Text;
        }
    }
}
