//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Limnor Studio.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefaultNamespace
{
    using System;
    using System.Xml;
    using System.Text;
    using System.Collections.Generic;
    using Limnor.Drawing2D;
    using System.Drawing;
    using System.IO;
    using System.Windows.Forms;
    
    public class Form2 : Limnor.Drawing2D.DrawingPage
    {
        private static Form2 _DefaultForm;
        private string valueOfSlideFolder;
        private short valueOfSlideNumber;
        private string valueOfSlideName;
        /// <summary>
        /// </summary>
        public Form2()
        {
            this.InitializeComponent();
        }
        public static Form2 DefaultForm
        {
            get
            {
                if (((_DefaultForm == null) 
                            || (_DefaultForm.IsDisposed || _DefaultForm.Disposing)))
                {
                    _DefaultForm = new Form2();
                }
                return _DefaultForm;
            }
        }
        public virtual string SlideFolder
        {
            get
            {
                return this.valueOfSlideFolder;
            }
            set
            {
                this.valueOfSlideFolder = value;
            }
        }
        public virtual short SlideNumber
        {
            get
            {
                return this.valueOfSlideNumber;
            }
            set
            {
                this.valueOfSlideNumber = value;
            }
        }
        public virtual string SlideImageFilename
        {
            get
            {
                return System.IO.Path.Combine(this.SlideFolder, string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}{1}{2}{3}", new object[] {
                                this.SlideName,
                                "_",
                                this.SlideNumber,
                                ".jpg"}));
            }
        }
        public virtual string SlideName
        {
            get
            {
                return this.valueOfSlideName;
            }
            set
            {
                this.valueOfSlideName = value;
            }
        }
        public virtual string SlideFilePath
        {
            get
            {
                return System.IO.Path.Combine(this.SlideFolder, string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}{1}{2}{3}", new object[] {
                                this.SlideName,
                                "_",
                                this.SlideNumber,
                                ".xml"}));
            }
        }
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            this.SuspendLayout();
            // 
            // Form2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.ClientSize = new System.Drawing.Size(121, 39);
            this.DrawingLayerList = ((Limnor.Drawing2D.DrawingLayerHeaderList)(resources.GetObject("$this.DrawingLayerList")));
            this.Name = "Form2";
            this.Text = "Slide";
            this.ResumeLayout(false);
        }
        /// <summary>
        /// </summary>
        /// <param name="slideFolder"></param>
        /// <param name="SlideIndex"></param>
        /// <param name="SlideName"></param>
        public virtual void LoadSlide(string slideFolder, short SlideIndex, string SlideName)
        {
            this.SlideFolder = slideFolder;
            this.SlideNumber = SlideIndex;
            this.SlideName = SlideName;
            if (System.IO.File.Exists(this.SlideImageFilename))
            {
                this.BackgroundImage = System.Drawing.Image.FromFile(this.SlideImageFilename);
            }
            if (System.IO.File.Exists(this.SlideFilePath))
            {
                this.LoadDrawingsFromFile(this.SlideFilePath);
            }
        }
    }
}
