//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limnor.WebBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limnor.WebBuilder.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _cancel {
            get {
                object obj = ResourceManager.GetObject("_cancel", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _newIcon {
            get {
                object obj = ResourceManager.GetObject("_newIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _ok {
            get {
                object obj = ResourceManager.GetObject("_ok", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap datepicker16 {
            get {
                object obj = ResourceManager.GetObject("datepicker16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FileBrowseButton {
            get {
                object obj = ResourceManager.GetObject("FileBrowseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //htmlElement: a div for holding the treeview.
        ///JsonDataBinding.CreateFileBrowser = function(htmlElement, rootFolder, rootName, filetypes, dontInit) {
        ///	var _rootUrl;
        ///	var _table;
        ///	var _divFolders;
        ///	var _divFiles;
        ///	var _colorSelectedFile = &apos;#ADD8E6&apos;;
        ///	var _root;
        ///	var _selectedFile;
        ///	var _inited = false;
        ///	var _fileSelectionHandlers = new Array();
        ///	_initFolders();
        ///	function _initFolders() {
        ///		_rootUrl = &apos;&apos;; // window.location.protocol + &apos;//&apos; + window.location.host;
        ///		if (rootFolder &amp;&amp; rootFolder.l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Filebrowser {
            get {
                return ResourceManager.GetString("Filebrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Filebrowser.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///﻿
        ///JsonDataBinding.CreateFileBrowser=function(htmlElement,rootFolder,rootName,filetypes,dontInit){var _rootUrl;var _table;var _divFolders;var _divFiles;var _colorSelectedFile=&apos;#ADD8E6&apos;;var _root;var _selectedFile;var _inited=false;var _fileSelectionHandlers=new Array();_initFolders();function _initFolders(){_rootUrl=&apos;&apos;;if(rootFolder&amp;&amp;rootFolder.length&gt;0){if(rootFolder.charAt(0)==&apos;/&apos;){_rootUrl=_rootUrl+rootFolder;}
        ///els [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Filebrowser_min {
            get {
                return ResourceManager.GetString("Filebrowser_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///include_once &apos;fileutility.php&apos;;
        ///
        ///class HtmlFileBrowser extends LimnorPhpFileUtilit
        ///{
        ///	function __construct($name)
        ///	{
        ///		parent::__construct($name);
        ///	}
        ///	public function loadFiles($path, $filetypes, $phpFolderName)
        ///	{
        ///		$this-&gt;DEBUG = $GLOBALS[&quot;debug&quot;];
        ///		$files = array();
        ///		// &apos;.&apos; for current
        ///		$dir = $this-&gt;getPhysicalPath($path, $phpFolderName);
        ///		if ($this-&gt;DEBUG)
        ///		{
        ///			echo &quot;start of listing files from &quot;.$dir.&quot;:============= &lt;br&gt;&quot;;
        ///		}
        ///		$di = new DirectoryIterator($dir);
        ///		fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string filebrowser_php {
            get {
                return ResourceManager.GetString("filebrowser_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///class HtmlFileUpload
        ///{
        ///	public $Filename;
        ///	public $FileSize;
        ///	public $FileType;
        ///	public $FilePathOnServer;
        ///	public $FileError;
        ///	public $FileErrorText;
        ///	public $FilePathSaved;
        ///	public $ObjectName;
        ///	public $FileUploaded;
        ///	public $MaximumFileSize;
        ///	public $Overwrite;
        ///	
        ///	function __construct($name)
        ///	{
        ///		$this-&gt;ObjectName = $name;
        ///		$this-&gt;FileUploaded = false;
        ///		$this-&gt;MaximumFileSize = 0;
        ///		$this-&gt;Overwrite = true;
        ///		if(isset($_FILES))
        ///		{
        ///			if(count($_FILES))
        ///			{
        ///				$this-&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileUploadItem_php {
            get {
                return ResourceManager.GetString("FileUploadItem_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///include_once &apos;JsonProcessPage.php&apos;;
        ///include_once &apos;FastJSON.class.php&apos;;
        ///include_once &apos;jsonDataBind.php&apos;;
        ///
        ///function CombinePath($p1, $p2)
        ///{
        ///	if(strlen($p1) == 0)
        ///		return $p2;
        ///	if(strlen($p2) == 0)
        ///		return $p1;
        ///	if($p2{0} == &apos;/&apos; || $p2{0} == &apos;\\&apos;)
        ///	{
        ///		if($p1{strlen($p1)-1} == &apos;/&apos; || $p1{strlen($p1)-1} == &apos;\\&apos;)
        ///		{
        ///			return $p1.substr($p2, 1);
        ///		}
        ///		else
        ///		{
        ///			return $p1.$p2;
        ///		}
        ///	}
        ///	else
        ///	{
        ///		if($p1{strlen($p1)-1} == &apos;/&apos; || $p1{strlen($p1)-1} == &apos;\\&apos;)
        ///		{
        ///			return $p1.$p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fileutility_php {
            get {
                return ResourceManager.GetString("fileutility_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderBrowser {
            get {
                object obj = ResourceManager.GetObject("folderBrowser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap googlemap {
            get {
                object obj = ResourceManager.GetObject("googlemap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///	Html Editor Library -- JavaScript
        ///	Copyright Longflow Enterprises Ltd -- Invention ideas: David Ge
        ///	2011
        ///
        ///*/
        ///var limnorHtmlEditorClient = limnorHtmlEditorClient || {
        ///	limnorDynaStyleTitle: &apos;dyStyle8831932&apos;,
        ///	pageCommentFrameId: &apos;pcf8831932&apos;,
        ///	getPageStarterNode: function (create) {
        ///		var stData;
        ///		var ss = document.getElementsByTagName(&apos;script&apos;);
        ///		if (ss) {
        ///			for (var i = 0; i &lt; ss.length; i++) {
        ///				var s = ss[i].getAttribute(&apos;src&apos;);
        ///				if (s) {
        ///					var p = s.lastIndexOf(&apos;/&apos;);
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlEditorClient {
            get {
                return ResourceManager.GetString("htmlEditorClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // htmlEditorClient.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///var limnorHtmlEditorClient=limnorHtmlEditorClient||{limnorDynaStyleTitle:&apos;dyStyle8831932&apos;,pageCommentFrameId:&apos;pcf8831932&apos;,getPageStarterNode:function(create){var stData;var ss=document.getElementsByTagName(&apos;script&apos;);if(ss){for(var i=0;i&lt;ss.length;i++){var s=ss[i].getAttribute(&apos;src&apos;);if(s){var p=s.lastIndexOf(&apos;/&apos;);if(p&gt;=0){s=s.substr(p+1);}
        ///p=s.lastIndexOf(&apos;\\&apos;);if(p&gt;=0){s=s.substr(p+1);}
        ///p=s.indexOf(&apos;?&apos;);if(p&gt;=0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmleditorClient_min {
            get {
                return ResourceManager.GetString("htmleditorClient_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Html Editor Library -- JavaScript
        ///Copyright Longflow Enterprises Ltd
        ///2011
        ///
        ///Use a DIV to do HTML input
        ///*/
        ///var limnorHtmlEditorDIV = limnorHtmlEditorDIV || {
        ///	loading: false,
        ///	loaded: false,
        ///	loadLibs: function(divs) {
        ///		if (!limnorHtmlEditorDIV.loaded) {
        ///			if (!limnorHtmlEditorDIV.loading) {
        ///				limnorHtmlEditorDIV.loading = true;
        ///				var editorFiles = new Array();
        ///				var loadingJson = false;
        ///				var loadingColor = false;
        ///				var loadingDb = false;
        ///				var loadingEditor = false;
        ///				v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlEditorDiv {
            get {
                return ResourceManager.GetString("htmlEditorDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // htmleditorDiv.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///var limnorHtmlEditorDIV=limnorHtmlEditorDIV||{loading:false,loaded:false,loadLibs:function(divs){if(!limnorHtmlEditorDIV.loaded){if(!limnorHtmlEditorDIV.loading){limnorHtmlEditorDIV.loading=true;var editorFiles=new Array();var loadingJson=false;var loadingColor=false;var loadingDb=false;var loadingEditor=false;var loadingClient=false;var loadingStarter=false;var loadingModal=false;function loadjsfile(f){var head=docu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmleditorDiv_min {
            get {
                return ResourceManager.GetString("htmleditorDiv_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///	Html Editor Library -- JavaScript
        ///	Copyright Longflow Enterprises Ltd
        ///	2011
        ///
        ///*/
        ///
        ///var limnorHtmlEditor = limnorHtmlEditor || {
        ///	serverType: &apos;php&apos;,
        ///	showMessage: function (msg) {
        ///		if (!document.divWaitMessage) {
        ///			document.divWaitMessage = document.createElement(&apos;div&apos;);
        ///			document.divWaitMessage.style.width = &apos;500px&apos;;
        ///			document.divWaitMessage.style.height = &apos;309px&apos;;
        ///			document.divWaitMessage.style.borderStyle = &apos;solid&apos;;
        ///			document.divWaitMessage.style.borderRadius = &apos;20px&apos;;
        ///			docum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmlEditorStarter {
            get {
                return ResourceManager.GetString("htmlEditorStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // htmlEditorStarter.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///var limnorHtmlEditor=limnorHtmlEditor||{serverType:&apos;php&apos;,showMessage:function(msg){if(!document.divWaitMessage){document.divWaitMessage=document.createElement(&apos;div&apos;);document.divWaitMessage.style.width=&apos;500px&apos;;document.divWaitMessage.style.height=&apos;309px&apos;;document.divWaitMessage.style.borderStyle=&apos;solid&apos;;document.divWaitMessage.style.borderRadius=&apos;20px&apos;;document.divWaitMessage.style.position=&apos;absolute&apos;;document.di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmleditorStarter_min {
            get {
                return ResourceManager.GetString("htmleditorStarter_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var triedCount = 0;
        ///function insertMouseCatcher() {
        ///	var me;
        ///	if (typeof (window.parent.limnorHtmlEditorClient) == &apos;undefined&apos;) {
        ///		triedCount++;
        ///		if (triedCount &gt; 10) {
        ///			alert(&apos;unable to plug watcher&apos;);
        ///			return;
        ///		}
        ///		setTimeout(insertMouseCatcher, 500);
        ///		return;
        ///	}
        ///	function getme(e) {
        ///		for (var i = 0; i &lt; e.children.length; i++) {
        ///			if (e.children[i].tagName.toLowerCase() == &apos;iframe&apos;) {
        ///				if (e.children[i].contentWindow == window) {
        ///					me = e.children[i];
        ///					break;
        ///				}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iframePlugin {
            get {
                return ResourceManager.GetString("iframePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // iframePlugin.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///var triedCount=0;function insertMouseCatcher(){var me;if(typeof(window.parent.limnorHtmlEditorClient)==&apos;undefined&apos;){triedCount++;if(triedCount&gt;10){alert(&apos;unable to plug watcher&apos;);return;}
        ///setTimeout(insertMouseCatcher,500);return;}
        ///function getme(e){for(var i=0;i&lt;e.children.length;i++){if(e.children[i].tagName.toLowerCase()==&apos;iframe&apos;){if(e.children[i].contentWindow==window){me=e.children[i];break;}}
        ///else{getme(e.ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iframePlugin_min {
            get {
                return ResourceManager.GetString("iframePlugin_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var limnorgooglemaps = limnorgooglemaps || {};
        ///limnorgooglemaps.createLocalUUID = function () {
        ///	return &apos;xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx&apos;.replace(/[xy]/g, function (c) {
        ///		var r = Math.random() * 16 | 0, v = c == &apos;x&apos; ? r : (r &amp; 0x3 | 0x8);
        ///		return v.toString(16);
        ///	});
        ///}
        ///limnorgooglemaps.showInfoWindow = function (marker, htmlInfo, maxWidth) {
        ///	if (marker.infoWin) {
        ///		marker.infoWin.setContent(htmlInfo);
        ///	}
        ///	else {
        ///		marker.infoWin = new google.maps.InfoWindow({ content: htmlInfo, maxWidth: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string limnorgooglemaps {
            get {
                return ResourceManager.GetString("limnorgooglemaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // limnorgooglemaps.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///﻿var limnorgooglemaps=limnorgooglemaps||{};limnorgooglemaps.createLocalUUID=function(){return&apos;xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx&apos;.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c==&apos;x&apos;?r:(r&amp;0x3|0x8);return v.toString(16);});}
        ///limnorgooglemaps.showInfoWindow=function(marker,htmlInfo,maxWidth){if(marker.infoWin){marker.infoWin.setContent(htmlInfo);}
        ///else{marker.infoWin=new google.maps.InfoWindow({content: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string limnorgooglemaps_min {
            get {
                return ResourceManager.GetString("limnorgooglemaps_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article.tabsClass
        ///{
        ///	position: absolute;
        ///	display: block;
        ///	left:100px;
        ///	top:60px;
        ///	width: 400px;
        ///	height: 240px;
        ///	margin: 2em auto;
        ///}
        ///article.tabsClass section
        ///{
        ///	position: absolute;
        ///	display: block;
        ///	top: 10px;
        ///	left: 0;
        ///	width: 400px;
        ///	height: 200px;
        ///	padding: 10px 20px;
        ///	background-color: #ddd;
        ///	border-radius: 5px;
        ///	box-shadow: 0 3px 3px rgba(0,0,0,0.1);
        ///	z-index: 0;
        ///}
        ///article.tabsClass section:first-child
        ///{
        ///	z-index: 1;
        ///}
        ///article.tabsClass section h2
        ///{
        ///	position: absolute;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string limnortabs {
            get {
                return ResourceManager.GetString("limnortabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var limnorUtility = limnorUtility || {};
        ///limnorUtility.replaceAll = function(s, key, value) {
        ///    if (key != value) {
        ///        while (s.indexOf(key) &gt;= 0) {
        ///            s = s.replace(key, value);
        ///        }
        ///    }
        ///    return s;
        ///}
        ///limnorUtility.RegExpQuote = function(str) {
        ///    return str.replace(/([.?*+^$[\]\\(){}|-])/g, &quot;\\$1&quot;);
        ///};
        ///limnorUtility.string = function(value, fields) {
        ///    var _value = value;
        ///    var _fields = fields;
        ///    return {
        ///        setProperty: function(key, val) {
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string limnorUtilString {
            get {
                return ResourceManager.GetString("limnorUtilString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // limnorUtilityString.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///﻿var limnorUtility=limnorUtility||{};limnorUtility.replaceAll=function(s,key,value){if(key!=value){while(s.indexOf(key)&gt;=0){s=s.replace(key,value);}}
        ///return s;}
        ///limnorUtility.RegExpQuote=function(str){return str.replace(/([.?*+^$[\]\\(){}|-])/g,&quot;\\$1&quot;);};limnorUtility.string=function(value,fields){var _value=value;var _fields=fields;return{setProperty:function(key,val){_fields[key]=val;},getProperty:function( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string limnorUtilString_min {
            get {
                return ResourceManager.GetString("limnorUtilString_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //htmlElement: a table for holding the top level menus.
        ///JsonDataBinding.CreateMenu = function(htmlElement) {
        ///    var _htmlTable = htmlElement;
        ///    var _selectedId;
        ///    var _selectedText;
        ///    hideSubMenus = function(subMenuTable) {
        ///        if (subMenuTable) {
        ///            subMenuTable.style.display = &apos;none&apos;;
        ///            var tds = subMenuTable.getElementsByTagName(&apos;td&apos;);
        ///            if (tds) {
        ///                for (var i = 0; i &lt; tds.length; i++) {
        ///                    if (tds[i].isMenu) {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // menu.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///﻿
        ///JsonDataBinding.CreateMenu=function(htmlElement){var _htmlTable=htmlElement;var _selectedId;var _selectedText;hideSubMenus=function(subMenuTable){if(subMenuTable){subMenuTable.style.display=&apos;none&apos;;var tds=subMenuTable.getElementsByTagName(&apos;td&apos;);if(tds){for(var i=0;i&lt;tds.length;i++){if(tds[i].isMenu){if(tds[i].jsData){var t=tds[i].jsData.getSubMenuTable();if(t){hideSubMenus(t);}}}}}}}
        ///hideMenus=function(){var tbls=document [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string menu_min {
            get {
                return ResourceManager.GetString("menu_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //htmlElement: a div for holding the treeview.
        ///JsonDataBinding.CreateTreeView = function(htmlElement) {
        ///	var _div = htmlElement;
        ///	var _nodeSelectionHandlers = new Array();
        ///	var _readOnly = true;
        ///	var _jsTable;
        ///	var _loadingMsg;
        ///	//var _existOnvalueChange;
        ///	var nodenameIdx = -1;
        ///	var textIdx = -1;
        ///	var imageIdx = -1;
        ///	var nodedataIdx = -1;
        ///	_div.mouseOverColor = &apos;#c0ffc0&apos;;
        ///	_div.nodeBackColor = &apos;White&apos;;
        ///	_div.selectedNodeColor = &apos;#c0c0ff&apos;;
        ///	_div.isTreeView = true;
        ///	//
        ///	function _selectNode(n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string treeview {
            get {
                return ResourceManager.GetString("treeview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // treeview.js 2012-01-09 Copyright Longflow Enterprises Ltd. http://www.limnor.com
        ///
        ///JsonDataBinding.CreateTreeView=function(htmlElement){var _div=htmlElement;var _nodeSelectionHandlers=new Array();var _readOnly=true;var _jsTable;var _loadingMsg;var nodenameIdx=-1;var textIdx=-1;var imageIdx=-1;var nodedataIdx=-1;_div.mouseOverColor=&apos;#c0ffc0&apos;;_div.nodeBackColor=&apos;White&apos;;_div.selectedNodeColor=&apos;#c0c0ff&apos;;_div.isTreeView=true;function _selectNode(nd){if(_div.selectedNode){_div.selectedNode.isSelected=false;_d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string treeview_min {
            get {
                return ResourceManager.GetString("treeview_min", resourceCulture);
            }
        }
    }
}
