//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimnorDatabase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LimnorDatabase.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _cancel {
            get {
                object obj = ResourceManager.GetObject("_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _erase {
            get {
                object obj = ResourceManager.GetObject("_erase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _help {
            get {
                object obj = ResourceManager.GetObject("_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _helpIcon {
            get {
                object obj = ResourceManager.GetObject("_helpIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _mssql {
            get {
                object obj = ResourceManager.GetObject("_mssql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _newIcon {
            get {
                object obj = ResourceManager.GetObject("_newIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _newItem {
            get {
                object obj = ResourceManager.GetObject("_newItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {null}.
        /// </summary>
        internal static string _null {
            get {
                return ResourceManager.GetString("_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _ok {
            get {
                object obj = ResourceManager.GetObject("_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _removeFromList {
            get {
                object obj = ResourceManager.GetObject("_removeFromList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _select {
            get {
                object obj = ResourceManager.GetObject("_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New table Join field.
        /// </summary>
        internal static string addT0 {
            get {
                return ResourceManager.GetString("addT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join-to table.
        /// </summary>
        internal static string addT1 {
            get {
                return ResourceManager.GetString("addT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join-to field.
        /// </summary>
        internal static string addT2 {
            get {
                return ResourceManager.GetString("addT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all field joins are fully defined..
        /// </summary>
        internal static string addT3 {
            get {
                return ResourceManager.GetString("addT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No field joins are defined..
        /// </summary>
        internal static string addT4 {
            get {
                return ResourceManager.GetString("addT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this field?.
        /// </summary>
        internal static string askDeleteField {
            get {
                return ResourceManager.GetString("askDeleteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connect_invalid {
            get {
                object obj = ResourceManager.GetObject("connect_invalid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connect_ok {
            get {
                object obj = ResourceManager.GetObject("connect_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0{\fonttbl{\f0\fswiss\fcharset0 Arial;}{\f1\fswiss\fprq2\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\lang1033\f0\fs20\par
        ///\cf1\f1\fs32 Connection Manager\cf0\f0\fs20\par
        ///\par
        ///The Connection Manager is an application for managing all database connections installed on a computer.\par
        ///Each database connection is identified by a Guid. One database connection may be shared by many applications. Changing a database  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConnectionManager {
            get {
                return ResourceManager.GetString("ConnectionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap datagrid {
            get {
                object obj = ResourceManager.GetObject("datagrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Database Connection.
        /// </summary>
        internal static string dbConnection {
            get {
                return ResourceManager.GetString("dbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New table name.
        /// </summary>
        internal static string dbMsg0 {
            get {
                return ResourceManager.GetString("dbMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table name is in use.
        /// </summary>
        internal static string dbMsg1 {
            get {
                return ResourceManager.GetString("dbMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this field?.
        /// </summary>
        internal static string dbMsg2 {
            get {
                return ResourceManager.GetString("dbMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to de-link this table as a child?.
        /// </summary>
        internal static string dbMsg3 {
            get {
                return ResourceManager.GetString("dbMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation not found.
        /// </summary>
        internal static string dbMsg4 {
            get {
                return ResourceManager.GetString("dbMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore the database from the backup. You may manually copy the backup file to the database file..
        /// </summary>
        internal static string dbMsg5 {
            get {
                return ResourceManager.GetString("dbMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file:.
        /// </summary>
        internal static string dbMsg6 {
            get {
                return ResourceManager.GetString("dbMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file:.
        /// </summary>
        internal static string dbMsg7 {
            get {
                return ResourceManager.GetString("dbMsg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del_all {
            get {
                object obj = ResourceManager.GetObject("del_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to de-link this table as a child?.
        /// </summary>
        internal static string deLinkTbl {
            get {
                return ResourceManager.GetString("deLinkTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delItem {
            get {
                object obj = ResourceManager.GetObject("delItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Group by&apos; fields not specified.
        /// </summary>
        internal static string Err_group_field {
            get {
                return ResourceManager.GetString("Err_group_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name not specified.
        /// </summary>
        internal static string fieldNameMissing {
            get {
                return ResourceManager.GetString("fieldNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all child table foreign key fields specified.
        /// </summary>
        internal static string fkMissing {
            get {
                return ResourceManager.GetString("fkMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldName.
        /// </summary>
        internal static string flds0 {
            get {
                return ResourceManager.GetString("flds0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one Identity field is allowed.
        /// </summary>
        internal static string flds1 {
            get {
                return ResourceManager.GetString("flds1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType.
        /// </summary>
        internal static string flds2 {
            get {
                return ResourceManager.GetString("flds2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string flds3 {
            get {
                return ResourceManager.GetString("flds3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one Timestamp field is allowed.
        /// </summary>
        internal static string flds4 {
            get {
                return ResourceManager.GetString("flds4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index name cannot be empty.
        /// </summary>
        internal static string indexNameMissing {
            get {
                return ResourceManager.GetString("indexNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok_up {
            get {
                object obj = ResourceManager.GetObject("ok_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name.
        /// </summary>
        internal static string ParamName {
            get {
                return ResourceManager.GetString("ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qry {
            get {
                object obj = ResourceManager.GetObject("qry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation not found.
        /// </summary>
        internal static string relNotFound {
            get {
                return ResourceManager.GetString("relNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select fields first.
        /// </summary>
        internal static string SelFlds {
            get {
                return ResourceManager.GetString("SelFlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap test {
            get {
                object obj = ResourceManager.GetObject("test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test value.
        /// </summary>
        internal static string TestValue {
            get {
                return ResourceManager.GetString("TestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet Database Driver is used, which is a 32-bit software..
        /// </summary>
        internal static string UseJet {
            get {
                return ResourceManager.GetString("UseJet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string w0 {
            get {
                return ResourceManager.GetString("w0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin with.
        /// </summary>
        internal static string w1 {
            get {
                return ResourceManager.GetString("w1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end with.
        /// </summary>
        internal static string w2 {
            get {
                return ResourceManager.GetString("w2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select operation first.
        /// </summary>
        internal static string w3 {
            get {
                return ResourceManager.GetString("w3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select field.
        /// </summary>
        internal static string w4 {
            get {
                return ResourceManager.GetString("w4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value field not selected.
        /// </summary>
        internal static string w5 {
            get {
                return ResourceManager.GetString("w5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name missing.
        /// </summary>
        internal static string w6 {
            get {
                return ResourceManager.GetString("w6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value not given.
        /// </summary>
        internal static string w7 {
            get {
                return ResourceManager.GetString("w7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///class WebLoginManager
        ///{
        ///	public $myname;
        ///	public $NameDelimiterBegin;
        ///	public $NameDelimiterEnd;
        ///	public $FailedMessageLableId;
        ///	public $InactivityMinutes;
        ///	public $LoginFailedMessage;
        ///	public $UserAccountIdFieldName;
        ///	public $UserAccountLoginFieldName;
        ///	public $UserAccountPasswordFieldName;
        ///	public $UserAccountSaltFieldName;
        ///	public $UserAccountLevelFieldName;
        ///	public $UserAccountTableName;
        ///	public $UserAccountResetCodeFieldName;
        ///	public $UserAccountResetCodeTimeFieldName;
        ///	public $j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebLoginManager_php {
            get {
                return ResourceManager.GetString("WebLoginManager_php", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
